version: '3.8'
services:
  nest-api:
    container_name: nest-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - postgres
    env_file:
      - .env.docker

  postgres:
    image: postgres:15.1
    container_name: db
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=$${POSTGRES_DB:?err}
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=$${POSTGRES_USER:?err}
      - POSTGRES_PASSWORD=$${POSTGRES_PASSWORD:?err}

  pgadmin:
    image: dpage/pgadmin4:6.20
    environment:
        PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
        PGADMIN_DEFAULT_PASSWORD: admin
        PGADMIN_LISTEN_PORT: 80
    ports:
        - 15432:80
    volumes:
        - pgadmin2:/var/lib/pgadmin
    depends_on:
        - postgres

    
volumes:
  postgres:
    name: nest-db
  pgadmin2:
    name: pgadmin-db